STATUS_BOOKED="Booked"
STATUS_COLLECTED="Collected"
STATUS_COLLECTORALLOCATED="Collector Allocated"
STATUS_PENDING="Pending" 
STATUS_NA="NA"
ROLE_HOUSEOWNER=1
ROLE_SUPERADMIN=2
ROLE_ADMIN=3
ROLE_SUPERVISOR=4
STATUS_PAYMENT_PENDING=0
DATE_FORMAT="%m/%d/%Y"
WASTE_PLASTIC = 1
WASTE_FOOD = 2
WASTE_EWASTE = 3
WASTE_METAL = 4
PAYMENT_STATUS ={
    "PAID":1,
    "UNPAID":0
}
ROLES = {
    "ADMIN":"Admin",
    "SUPERADMIN":"Super Admin",
    "SUPERVISOR":"Supervisor"

}